Iter20
shulganew/shear pull request #11
Opened 2024-03-11 15:21 UTC by shulganew

sprint 8 iter20

2024-03-12 18:08 UTC, maxlyaptsev commented on logout_all.txt
> +Analizers from go/analysis/passes:  47
лишнее добавилось

2024-03-12 18:22 UTC, maxlyaptsev requested changes

2024-03-12 18:22 UTC, maxlyaptsev commented on cmd/staticlint/errcheckanalyzer.go
> +package main
сам анализатор это по сути пакет. Причем который может переиспользоваться в других проектах. Кажется уже писал, cmd используется только для запуска кода. Там не должны лежать какие-то сторонние пакеты

2024-03-12 18:22 UTC, maxlyaptsev commented on internal/app/init.go
> +	fmt.Printf("Build version: <%s>\nBuild date: <%s>\nBuild commit: <%s>\n", version, date, commit)
есть способ удобней - Println который добавляет переносы - читается легче
```
        fmt.Println("Build version:", buildVersion)
	fmt.Println("Build date:", buildDate)
	fmt.Println("Build commit:", buildCommit)
	```

2024-03-12 18:22 UTC, maxlyaptsev commented on internal/app/init.go
> +		version = "N/A"
глобальные переменные инициализируются сразу со значением. В твоем случае это "". Можно просто сразу задать там нормальное значение (N/A)

2024-03-12 18:22 UTC, maxlyaptsev commented on cmd/staticlint/docgen.go
> +package main
не понял чем отличается docgen от doc. Это дубль или зачем он нужен?

2024-03-12 18:22 UTC, maxlyaptsev commented on cmd/staticlint/errcheckanalyzer.go
> +func run(pass *analysis.Pass) (interface{}, error) {
выше собирается мультичекер, а это отдельный анализатор, его нужно подключать точно так же как другие

2024-03-12 18:22 UTC, maxlyaptsev commented on cmd/staticlint/errcheckanalyzer.go
> +		docgen(analyzers...)
а зачем документация в этой же команде? Подобные условия очень путают. Код пытается сразу две функции выполнить - значит это должны быть две разные команды

2024-03-14 07:47 UTC, shulganew commented on cmd/staticlint/errcheckanalyzer.go
> +package main
Да, я долго думал, куда его поместить. Вообще я хотел сделать отдельными модулями как staticlint, так и анализатор os.Exit, так как по моему пониманию они вообще не должны быть в шортенере. Но тогда надо создавать еще два репозитория в github, а это будет очень неудобно и непонятно для работы с инкрементом. Сейчас перенес обе анализатора в pkg, не знаю насколько это правильный вариант. Да, с cmd был худший вариант)

2024-03-14 07:48 UTC, shulganew commented on internal/app/init.go
> +	fmt.Printf("Build version: <%s>\nBuild date: <%s>\nBuild commit: <%s>\n", version, date, commit)
Да, исправил.

2024-03-14 07:48 UTC, shulganew commented on internal/app/init.go
> +		version = "N/A"
Что-то не подумал, убрал эту кучу if.

2024-03-14 07:54 UTC, shulganew commented on cmd/staticlint/docgen.go
> +package main
Вообщем идея была такая - docgen.go генерит файл doc.go с документацией, чтобы вручную не добавлять 90+47 анализаторов. Фактически он нужен однократно, сейчас его можно удалить. Я сделал генерацию файла документации при вызове с флагом -d, сейчас убрал это, так как по факту это просто однократное выполнение команды для генерации и код этот лишний. Пометил как go build ignore, как скажешь, может лучше вообще удалить из проекта файл docgen.go.

2024-03-14 07:54 UTC, shulganew commented on cmd/staticlint/errcheckanalyzer.go
> +func run(pass *analysis.Pass) (interface{}, error) {
Разнес по пакетам, сделал все адекватно.

2024-03-14 07:55 UTC, shulganew commented on cmd/staticlint/errcheckanalyzer.go
> +		docgen(analyzers...)
Выпилил вообще эту генерацию. Я решил, что если это однократное генерирование файла, то в коде вообще не надо оставлять.

2024-03-14 08:16 UTC, maxlyaptsev approved these changes

2024-03-14 09:15 UTC, merged