iter23
shulganew/shear pull request #12
Opened 2024-03-23 19:24 UTC by shulganew

sprint 9 iter23

2024-03-24 23:43 UTC, maxlyaptsev requested changes

2024-03-24 23:43 UTC, maxlyaptsev commented on internal/web/server/server.go
> +func ShortenerServer(ctx context.Context, wgroot *sync.WaitGroup, wgdel *sync.WaitGroup, db *sql.DB, conf *config.Config, short *service.Shorten, del *service.Delete, componentsErrs chan error) {
очень уж много аргументов. Можно передавать такие параметры структурой

2024-03-24 23:43 UTC, maxlyaptsev commented on internal/app/shutdown.go
> +		wgdel.Wait()
Неправильные зависимости. Шатдаун зависит от деталей реализации. И при добавлении новых компонент придется добавлять сюда обработку завершения. Это первое. Второе - wait group в целом используется не для этого. Использовать блокировку канала было бы логичней.

вариантов что можно сделать много - можно вызывать методы Stop у каждого сервиса - они сами будут блокировать себя пока не завершатся

можно регистрировать каналы для завершений отдельной функцией, а при завершении вызывать функцию, которая будет эти каналы закрывать

Можно придумать еще много вариантов, но нужно отвязать эти сущности

2024-03-25 14:43 UTC, shulganew commented on internal/web/server/server.go
> +func ShortenerServer(ctx context.Context, wgroot *sync.WaitGroup, wgdel *sync.WaitGroup, db *sql.DB, conf *config.Config, short *service.Shorten, del *service.Delete, componentsErrs chan error) {
Я создание роутера в main поднял, стало меньше аргументов:

2024-03-25 15:33 UTC, shulganew commented on internal/app/shutdown.go
> +		wgdel.Wait()
Я убрал вообще все WG, из main. Создаю только одну в сервисе для асинхронного удаления урлов. Только этот сервис нужно ждать, он асинхронного удаляет урлы, поэтому я для него сделал метод Stop и ожидаю завершения его работы. Посмотри, правильно ли я тебя понял.

2024-03-25 15:54 UTC, maxlyaptsev commented on internal/app/shutdown.go
> +		wgdel.Wait()
В целом да, лучше. Можно сделать так чтобы шатдаун был универсальный и вообще вынести его в общедоступный пакет. А сами севрисы уже будут заботиться об их завершении. Соотв delCh chan service.DelBatch не будет в шатдауне который жестко привязывает к каналу удаления

2024-03-26 08:36 UTC, shulganew commented on internal/app/shutdown.go
> +		wgdel.Wait()
Попробовал так сделать, в shutdown передаю только контекст и функцию отмены. Сервисы сами себя завершают.

2024-04-02 12:44 UTC, merged