Iter5
shulganew/shear pull request #5
Opened 2023-11-02 16:40 UTC by shulganew

Add OS ENV

2023-11-08 17:27 UTC, maxlyaptsev requested changes

2023-11-08 17:27 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +var Urldb = map[string]string{}
не следует использовать глобальные переменные т.к. мапы предполагают конкурентный доступ и в целом это плохая практика

2023-11-08 17:27 UTC, maxlyaptsev commented on internal/app/config/go.mod
> +module config
не нужно делать config отдельным модулем
go.mod должен лежать только в корне проекта

2023-11-08 17:27 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +import (
нужно разнести проект по пакетам:
/cmd/main.go - отвечает только за запуск приложения
/interna/config - конфигурирование приложения
/internal/storage соответственно это хранилище
/internal/handlers - здесь api ручки

это примерная минимальная структура. Написать весь код в одном файле конечно физически возможно и это даже будет работать и для такого небольшого проекта это может быть достаточно. Но мы будем писать довольно большой проект, поэтому нужно заложить архитектуру

2023-11-08 17:27 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +	if exist {
в случае если нет, хотелось бы видеть обработку ситуации (404?)

2023-11-08 17:27 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +	answer += shortUrl
лучше использовать либо net/url - https://pkg.go.dev/net/url#URL.JoinPath
либо формировать url в одну строку - используя `fmt.Printf` например. А так можно потерять часть или не увидеть что здесь еще что-то добавляется

2023-11-08 17:27 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +	//answer := fmt.Sprintf("Method: %s\r\n", req.Method)
неиспользуемый код нужно удалить
еще советую по возможности настроить линтер - это не долго и об этом говорили в недавнем вебинаре, но если будут сложности, велком на 1-1

2023-11-12 18:23 UTC, shulganew commented on cmd/shortener/main.go
> +var Urldb = map[string]string{}
Максим, сделал отдельный пакет storage

2023-11-12 18:23 UTC, shulganew commented on internal/app/config/go.mod
> +module config
Понял, убрал

2023-11-12 18:23 UTC, shulganew commented on cmd/shortener/main.go
> +import (
Исправил

2023-11-12 18:24 UTC, shulganew commented on cmd/shortener/main.go
> +	//answer := fmt.Sprintf("Method: %s\r\n", req.Method)
Линтер завтра попробую сам доставить и запишусь сразу к вам 1-1.

2023-11-12 19:56 UTC, maxlyaptsev requested changes

2023-11-12 19:56 UTC, maxlyaptsev commented on internal/handlers/webhandl.go
> +	longUrl, exist := (*urldb)[shortUrl]
не стоит напрямую работать с внутренностями пакета storage - следует сделать публичные методы в нем и ими пользоваться

2023-11-12 19:56 UTC, maxlyaptsev commented on internal/storage/storage.go
> +var urldb map[string]url.URL = make(map[string]url.URL)
Лучше создавать структуру через конструктор и для нее создавать мапу. В текущем варианте это синглтон и создать например 2 стораджа будет невозможно

вторая проблема - глобальная переменная. Пока пакет конкретно такой - это не страшно. Но если он будет расширяться, переменная может быть случайно изменена. И найти ошибку будет очень сложно

2023-11-12 19:56 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +import (
в этом файле все еще можно лишнего - initApp и Route тоже можно вынести.
В идеале тут должно оставаться несколько строк - инициализируем приложение и запускаем, это не место для основного кода

2023-11-13 19:01 UTC, shulganew commented on cmd/shortener/main.go
> +import (
Вынес инициализацию проекта iniApp и Route, сделал такую структуру проекта:
    internal/core
    internal/storage
    internal/web/router
    internal/web/handlers
     internal/web
    internal/app/config
    internal/app/initapp
     internal/app
     internal

2023-11-13 19:02 UTC, shulganew commented on cmd/shortener/main.go
> +	if exist {
Исправил в коде:
`	if exist {

		res.Header().Set("Location", longURL.String())

		//set status code 307

		res.WriteHeader(http.StatusTemporaryRedirect)

	} else {

		res.WriteHeader(http.StatusNotFound)

	}`

2023-11-13 19:04 UTC, shulganew commented on cmd/shortener/main.go
> +	answer += shortUrl
Попробовал реализовать через https://pkg.go.dev/net/url#URL.JoinPath
Хотя так и не понял, как добавить протокол http, оставил как + "://"+

2023-11-13 19:06 UTC, shulganew commented on cmd/shortener/main.go
> +	//answer := fmt.Sprintf("Method: %s\r\n", req.Method)
Поставить удалось, пока падает с ошибкой `id go version '1.21.3': must match format 1.23\n`
Не пойму, почему он такую высокую версию GO требует. Завтра попробую сам разобраться, просто не успел добить.

2023-11-13 21:20 UTC, maxlyaptsev requested changes

2023-11-13 21:20 UTC, maxlyaptsev commented on internal/app/initapp/initapp.go
> +	log.Println("Server address: ", configApp.StartAddress)
Так, у нас есть пакет config. Почему не написать этот код там? Либо какая тогда цель пакета config если там нет того самого конфига?

2023-11-13 21:20 UTC, maxlyaptsev commented on internal/storage/storage.go
> +	}
лучше создать конструктор - функцию New которая будет инициализировать мапу

2023-11-13 21:20 UTC, maxlyaptsev commented on internal/core/utils.go
> +package utils
1.  имя пакета должно совпадать с именем директории
2. файл utils не говорит ничего о его назначении - лучше использовать функциональные имена - shortener например

2023-11-13 21:20 UTC, maxlyaptsev commented on internal/app/initapp/initapp.go
> +package initapp
```suggestion
package app
```
Пакет app а метод Init , так логичней. Если захочется добавить другой метод не придется переименовывать файл

2023-11-13 21:20 UTC, maxlyaptsev commented on internal/web/handlers/webhandl.go
> +package webhandl
```suggestion
package handlers
```
имя директории = имя пакета
лишнее и бессмысленное лучше не писать и делать названия короче

2023-11-13 21:20 UTC, maxlyaptsev commented on internal/web/handlers/webhandl.go
> +	}
```suggestion
	if exist {
		res.Header().Set("Location", longURL.String())
		//set status code 307
		res.WriteHeader(http.StatusTemporaryRedirect)
		
		return
	} 
	
	res.WriteHeader(http.StatusNotFound)
	
```
лишние else - не стоит использовать - приходится читать два условия вместо одного.

2023-11-14 18:09 UTC, shulganew commented on internal/app/initapp/initapp.go
> +	log.Println("Server address: ", configApp.StartAddress)
Перенес в пакет config, только у меня получилось, что app init()  полько инициализация конфига. Пока оставил так, может там еще что нужно будет инициализировать

2023-11-14 18:10 UTC, shulganew commented on internal/storage/storage.go
> +	}
Попробовал так сделать:
`func NewMapStorage() URLSetGet {
	return &MapStorage{storeURLs: make(map[string]url.URL)}
}`

2023-11-14 18:12 UTC, shulganew commented on internal/core/utils.go
> +package utils
Перенес в shotener, привыкаю к структуре пакета go, сейчас более стало понятно.

2023-11-14 18:12 UTC, shulganew commented on cmd/shortener/main.go
> +	//answer := fmt.Sprintf("Method: %s\r\n", req.Method)
Линтер настроил, все работает. Пока разбираюсь в ее выводе.

2023-11-15 14:33 UTC, maxlyaptsev commented on internal/storage/storage.go
> +	}
В целом лучше но не совсем то: сторедж не должен знать о том что в нем хранится - это довольно "тупой" инстурмент - сохрани (set) и верни (get) - в общем то и все. 

Почему это должен быть отдельный пакет? Саму реализацию стораджа мы можем заменить на другую - например хранить в файлах или в базе данных, а не в памяти. Если это одельный пакет, а клиентский код принимает для себя только интерфейс - замена произойдет очень легко

По поводу конкретных методов сохранения и получения уров -  это как раз некий сервис, который сможет сгенерировать короткую ссылку и застави сторендже ее сохранить. Так же этот сервис сможет забрать из стораджа ссылку и отформатировать так чтобы это был правильный url (подставит хост из конфига)

2023-11-15 17:50 UTC, shulganew commented on internal/storage/storage.go
> +	}
Попробовал сделать сервис работы c урлами, который в качестве параметра принимает интерфейс storaga. Storage инициализируется в app init, как я понимаю, если я теперь сделаю другой storage (бд например), то я сомгу его при инициализации легко поменять, так?
`func NewService(storage storage.StorageURL) *ServiceURL {
	return &ServiceURL{StoreURLs: storage}
}`

2023-11-15 19:20 UTC, maxlyaptsev requested changes

2023-11-15 19:20 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +	handler.SetConfig(configApp)
set/get не лучший вариант т.к. можно просто пропустить - если есть аргумент в конструкторе, то создать невалидную структуру просто не получится. А так это вполне возможно + усложняет код

2023-11-15 19:20 UTC, maxlyaptsev commented on internal/app/app.go
> +}
кажется весь этот метод является проксирующим и не нужен - можно сразу вызвывать config.InitConfig()там где это нужно

2023-11-16 15:57 UTC, shulganew commented on cmd/shortener/main.go
> +	handler.SetConfig(configApp)
Понял, убрал большую часть методов и сделал конструктор хендлера:
`func NewHandler(configApp *config.ConfigShear) *URLHandler {



	return &URLHandler{serviceURL: service.NewService(configApp.Storage), conf: configApp}

}`

2023-11-16 15:59 UTC, shulganew commented on internal/app/app.go
> +}
Да, в результе рефакторинг получился бессмысленным метод, убрал.

2023-11-16 20:19 UTC, maxlyaptsev commented on internal/storage/storage.go
> +	}
Верно, только интерфейс нужно в место реализации перенести, там где NewService(storage storage.StorageURL) - т.е. сам сервис знает какой ему нужен интерфейс. 

Можно предположить что сторедж это какой-то внешний пакет, который может меняться - если он изменится, мы все еще будем требовать интерфейс из него, но этот интерфейс может быть другим, тогда все поломается.

2023-11-16 20:29 UTC, maxlyaptsev commented on internal/shortener/shortener.go
> +package shortener
shortener.go можно перенести в services и это как раз будет один из сервисов. Можно оставить отдельно как сейчас, но тогда хотелось бы тут видеть остальную логику по сокращению ссылки - то что лежит в service/service.go - в целом не очень понятно что за сервис, лучше называть функциональными именами. Ну и дробление тут наверное лишнее т.к. оба эти пакета вместе работают

2023-11-16 20:29 UTC, maxlyaptsev commented on internal/web/netaddr/netaddr.go
> +func CheckAddress(address string) (host string, port string) {
я бы эту проверку убрал в config т.к. больше нигде и не используется, а значит как отдельный пакет нет смысла держать

2023-11-17 16:30 UTC, merged