Iter9
shulganew/shear pull request #6
Opened 2023-11-25 14:10 UTC by shulganew

Sprint 2

2023-11-27 22:08 UTC, maxlyaptsev requested changes

2023-11-27 22:08 UTC, maxlyaptsev commented on .github/workflows/shortenertest.yml
> +
этот файл не нужно менять

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/api/json.go
> +	zap.S().Infoln("Request long URL from JSON: ", request.LongURL)
это лучше убрать в мидлвару

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/api/json.go
> +	zap.S().Infoln("Server ansver with short URL in JSON: ", string(jsonURL))
тоже задача логера

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/api/json.go
> +func (u *HandlerAPI) SetAPI(res http.ResponseWriter, req *http.Request) {
а почему такое название выбрано? Кажется так будет лучше:
```suggestion
func (u *HandlerAPI) GetShortURL(res http.ResponseWriter, req *http.Request) {
```

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/api/json.go
> +package api
давай переименуем файл - лучше что-то более фукнциональное

Но вообще это тот же handlers - отдельно разбрасывать ручки по разным пакетам не стоит

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/service/shortener.go
> +	log.Println("Save long url: ", answerURL)
у нас есть полноценный логгер, стоит переписать все логи на него

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/service/shortener.go
> +	answerURL, _ = url.Parse(longStrURL)
```suggestion
	answerURL, err = url.Parse(longStrURL)
```
ошибки лучше не глушить - приводит к неожиданному поведению

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/shortener/shortener.go
> +	for i := 0; i < appconsts.ShortLength; i++ {
константы хорошо но я бы не стал в отдельный пакет выносить - большое количество зависимостей это не go-way. До выноса можно было пакет легко скопировать и переиспользовать, а так становится сложней

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/storage/storage.go
>  	}
нужно снизить алгоритмическую сложность до O(1) - не стоит перебирать все значения

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/web/handlers/middlewgzip.go
> +package handlers
лучше переместить в пакет middleware
В handlers храним только ручки и ничего более

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/web/handlers/middlewgzip.go
> +		if !strings.Contains(r.Header.Get(appconsts.AcceptEncoding), "gzip") {
то что клиент не поддерживает в ответе gzip не значит что он сам его не передал, лучше сдвинуть ниже это условие. Кроме того есть и другие кодировки

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/web/handlers/middlewgzip.go
> +		//r.Header.Set(appconsts.ContentEncoding, appconsts.ContentTypeJSON)
```suggestion
```

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/storage/storage.go
> +// }
```suggestion
```

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/web/handlers/url.go
> +	zap.S().Infoln("Get request: ", req.URL.Path)
это уже логируется в мидлваре

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/web/handlers/url.go
> +	zap.S().Infoln("Redirect to: ", longURL)
это тоже работа для логирующей мидлвары. Там можно проверить статус ответа и отреагировать на него соответствующим логом

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/web/handlers/url.go
> +	zap.S().Infoln("Server ansver with short URL: ", answerURL)
тоже задача мидлвары

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/web/router/router.go
> +	// })
```suggestion
```

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/web/validators/validatorurl.go
> +		zap.S().Infoln("Error parsing url whis shema: ", err, " return def localhost:8080")
```suggestion
		zap.S().ErrorKV....
```
Ошибки логируем как ошибки
Если с ошибкой жить можно - ставится Warn но вообще редко используется

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/web/validators/validatorurl.go
>  	host, port, err2 := net.SplitHostPort(strings.TrimSpace(link.Host))
```suggestion
	host, port, err := net.SplitHostPort(strings.TrimSpace(link.Host))
```
никаких err2 быть не должно - ошибка обрабатывается сразу - либо возвращаем либо нам она уже не нужна и переменную можно перезаписать

2023-11-27 22:08 UTC, maxlyaptsev commented on internal/web/validators/validatorurl.go
> +		zap.S().Infoln("Error split port: ", err, " return def localhost:8080 Host:", link.Host)
Ошибка, не инфо

2023-11-28 17:10 UTC, shulganew commented on .github/workflows/shortenertest.yml
> +
Случайно сломал, когда делал локальную проверку тестов. Исправлю как было.

2023-11-28 19:09 UTC, shulganew commented on internal/api/json.go
> +	zap.S().Infoln("Request long URL from JSON: ", request.LongURL)
Понял, исправил

2023-11-28 19:09 UTC, shulganew commented on internal/api/json.go
> +	zap.S().Infoln("Server ansver with short URL in JSON: ", string(jsonURL))
И это исправил

2023-11-28 19:18 UTC, shulganew commented on internal/api/json.go
> +func (u *HandlerAPI) SetAPI(res http.ResponseWriter, req *http.Request) {
Я так понял, что это REST и это устанавливаемое значение в API, согласен, так будет логичнее.

2023-11-28 19:25 UTC, shulganew commented on internal/api/json.go
> +package api
Да, я подумал, что раз это REST, то его как в api отдельный сделать, исправил.

2023-11-28 19:26 UTC, shulganew commented on internal/web/handlers/url.go
> +	zap.S().Infoln("Server ansver with short URL: ", answerURL)
Перенес

2023-11-28 19:28 UTC, shulganew commented on internal/service/shortener.go
> +	answerURL, _ = url.Parse(longStrURL)
Запомнил

2023-11-28 19:30 UTC, shulganew commented on internal/shortener/shortener.go
> +	for i := 0; i < appconsts.ShortLength; i++ {
Да, у меня вопрос по константам есть, как лучше организовать и что выносить в константы. Про организацию понял.

2023-11-28 20:00 UTC, shulganew commented on internal/storage/storage.go
>  	}
Воспользовался встроенной функцией поиска slices.IndexFunc

2023-11-28 20:06 UTC, shulganew commented on internal/web/handlers/middlewgzip.go
> +package handlers
Ясно

2023-11-28 20:14 UTC, shulganew commented on internal/web/handlers/middlewgzip.go
> +		if !strings.Contains(r.Header.Get(appconsts.AcceptEncoding), "gzip") {
Вот тут не очень понял, то есть клиент может передать сжатый файл, при этом в ответе ждать без сжатия или не в gzip формате, так?

2023-11-28 20:14 UTC, shulganew commented on internal/web/handlers/middlewgzip.go
> +		//r.Header.Set(appconsts.ContentEncoding, appconsts.ContentTypeJSON)
Да, буду следить за чистотой кода.

2023-11-28 20:22 UTC, shulganew commented on internal/web/handlers/url.go
> +	zap.S().Infoln("Redirect to: ", longURL)
Перенес в мадлварь

2023-11-28 20:23 UTC, shulganew commented on internal/web/validators/validatorurl.go
> +		zap.S().Infoln("Error parsing url whis shema: ", err, " return def localhost:8080")
Ясно

2023-11-28 20:23 UTC, shulganew commented on internal/web/validators/validatorurl.go
>  	host, port, err2 := net.SplitHostPort(strings.TrimSpace(link.Host))
Запомнил

2023-11-29 21:32 UTC, maxlyaptsev requested changes

2023-11-29 21:32 UTC, maxlyaptsev commented on internal/web/handlers/json.go
> +}
json лишнее т.к. это структура, а анотация, тегирование может много чего еще - например если добавить db: ... эта структура уже будет парсится при добавлении или чтении из базы данных. Так что лучше просто Request/Response - а внутри максимально повторять имена чтобы не было путаницы (хотя LongURL даже понятней)
```suggestion
type Request struct {
	URL string `json:"url"`
}
```

2023-11-29 21:32 UTC, maxlyaptsev commented on internal/service/shortener.go
> +	}
Бекап должен быть отдельным процессом. Т.е. мы работаем как и работали раньше - создаем короткие ссылки и сохраняем в память. Все как в первом спринте

Отдельный процесс периодически берет все данные из памяти и кладет в файл. Очень желательно чтобы еще и перед завершением приложения это происходило

Примерно так:

```go
	// создаем канал и указываем чтобы сигнал писался в него
	exit := make(chan os.Signal, 1)
	defer close(exit)
	// читаем сигнал и пишем его в канал
	signal.Notify(exit, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		// ждем когда будет сигнал
		<-exit
		fmt.Println("Получили сигнал завершения, сохраняем данные в файл")
		time.Sleep(time.Second)
		fmt.Println("Завершили")
	}()
	
	// запускаем наш http сервер
```

2023-12-01 16:11 UTC, maxlyaptsev approved these changes

2023-12-01 16:11 UTC, maxlyaptsev commented on internal/service/backuper.go
> +	signal.Notify(exit, syscall.SIGTERM, syscall.SIGQUIT, os.Interrupt)
как лучше - сигнал читать в main.go т.к. сигнал общий для всего приложения. А в свои сервисы прокидывать либо канал либо еще лучше контекст

Зачем контекст - когда получаем сигнал завершения - закрываем контекст 
```go
ctx, cancel := context.WithCancel(context.Background())
signal.Notify(exit, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		// ждем когда будет сигнал
		<-exit
		// отменяем контекст
		cancel()
}
```

прокидываем этот контекст везде и в сервисе проверяем через
```go
 <-ctx.Done()
 ```

2023-12-01 16:11 UTC, maxlyaptsev commented on internal/service/backuper.go
> +		shortj, err := json.Marshal(short)
можно оптимизировать не читая в отдельную переменную а сразу анмаршалить при чтении из файла - нужно восопльзоваться json.NewDecoder()

2023-12-01 18:54 UTC, shulganew commented on internal/service/backuper.go
> +		shortj, err := json.Marshal(short)
Сделал вот так:
`	shorts := []storage.Short{}
	dec := json.NewDecoder(file)
	for {
		var short storage.Short
		if err := dec.Decode(&short); err == io.EOF {
			break
		} else if err != nil {
			zap.S().Errorln("Error unmarshal data", err)
		}
		shorts = append(shorts, short)
	}`

2023-12-01 20:51 UTC, shulganew commented on internal/service/shortener.go
> +	}
Сделал две функции в сервисе backup - Shutdown и TimeBackup

2023-12-01 20:51 UTC, shulganew commented on internal/service/backuper.go
> +	signal.Notify(exit, syscall.SIGTERM, syscall.SIGQUIT, os.Interrupt)
Попробовал реализовать через Context

2023-12-04 17:43 UTC, merged