Iter13
shulganew/shear pull request #7
Opened 2023-12-12 05:14 UTC by shulganew

Sprint 3

2023-12-13 18:53 UTC, maxlyaptsev requested changes

2023-12-13 18:53 UTC, maxlyaptsev commented on internal/config/config.go
> +		db := InitDB(ctx, dsn)
это конфигурация, делать тут подключение к базе данных неправильно

2023-12-13 18:53 UTC, maxlyaptsev commented on internal/config/config.go
> +	dsn, exist := os.LookupEnv(("DATABASE_DSN"))
эту логику лучше вынести в отдельную функцию

2023-12-13 18:53 UTC, maxlyaptsev commented on internal/config/config.go
> +		go func() {
конфигурация не лучшее место для этого функционала

2023-12-13 18:53 UTC, maxlyaptsev commented on internal/service/backuper.go
>  		<-ctx.Done()
лучше если логика ловли завершения будет где-то сверху, а в сервисе просто вызывать метод Shutdown, который просто завершит конкретно этот сервис

2023-12-13 18:53 UTC, maxlyaptsev commented on internal/storage/db.go
> +	DB *sql.DB
```suggestion
	master *sql.DB
```
или connection

2023-12-13 18:53 UTC, maxlyaptsev commented on internal/web/handlers/batch.go
> +func (u *HandlerBatch) Batch(res http.ResponseWriter, req *http.Request) {
название не очень понятное т.к. не содержит действия - получить, добавить, обновить, удалить? Не понятно

2023-12-13 18:53 UTC, maxlyaptsev commented on internal/web/handlers/batch.go
> +	for i := 0; i < len(requests); i++ {
```suggestion
	for r, _ := range requests {
```
лишнее усложнение

2023-12-13 18:53 UTC, maxlyaptsev commented on internal/web/handlers/batch.go
> +			if id != -1 {
не понимаю что тут происходит. Долго смотрел на код, не понимаю. В связи с этим несколько комментариев - мы пишем код чтобы читать, почти всегда код именно читается, тут можно пропорцию 1-100 примерно обозначить - одну строку пишем, 100 читаем. Поэтому читаемость это очень важно

Второе. Мы получили ошибку - нужно отреагировать - залогировать иили вывести ошибку дальше, на этом все. Большой логики тут быть не должно

2023-12-13 18:53 UTC, maxlyaptsev commented on internal/web/handlers/json.go
> +	if err != nil {
аналогичный комментарий - если поучили ошибку в коде условия должно быть максимально небольшое количество действий

2023-12-15 12:52 UTC, maxlyaptsev commented on internal/storage/db.go
> +func (base *DB) Set(ctx context.Context, brief, origin string) error {
func New(config) {
    return &DB{
        dsn: 
        conf: 
    }
}


func (base *DB) Start(ctx context.Context) error {
// ждем 3 секунды - если не смогли стартовать - возвращаем ошибку
// читаем контекст ctx = context.WithTimeout(ctx, time.Second*3)
// <-ctx.Done(): return
}

2023-12-15 12:54 UTC, maxlyaptsev commented on internal/web/handlers/batch.go
> +}
конструктор самый первый, под самой структурой

2023-12-15 12:56 UTC, maxlyaptsev commented on internal/web/handlers/batch.go
> +func NewHandlerBatch(configApp *config.App) *HandlerBatch {
```suggestion
type Storage interface {
    Set() error
    Get() Item
}
func NewHandlerBatch(configApp *config.App, s Storage) *HandlerBatch {
```

2023-12-15 13:00 UTC, maxlyaptsev commented on internal/web/handlers/ping.go
> +func NewDB(configApp *config.App) *Ping {
```suggestion
type Pinger interface {
    ping()
}
func NewPingHandler(configApp Pinger) *Ping {

```

2023-12-20 14:09 UTC, shulganew commented on internal/config/config.go
> +		db := InitDB(ctx, dsn)
Создал пакет инициализации приложения, перенес все туда. app/init.go

2023-12-20 14:09 UTC, shulganew commented on internal/config/config.go
> +	dsn, exist := os.LookupEnv(("DATABASE_DSN"))
Вынес в инит приложения

2023-12-20 14:12 UTC, shulganew commented on internal/config/config.go
> +		go func() {
Перенес в main

2023-12-20 14:12 UTC, shulganew commented on internal/service/backuper.go
>  		<-ctx.Done()
Тоже вынес в main, убрал горутину из Shutdown

2023-12-20 14:14 UTC, shulganew commented on internal/web/handlers/batch.go
> +func (u *HandlerBatch) Batch(res http.ResponseWriter, req *http.Request) {
Переименовал в BatchSet

2023-12-20 14:54 UTC, shulganew commented on internal/web/handlers/batch.go
> +			if id != -1 {
Вообще сделал иначе, теперь ID возвращается в ошибке и сразу формируем ответ

2023-12-20 15:48 UTC, shulganew commented on internal/storage/db.go
> +func (base *DB) Set(ctx context.Context, brief, origin string) error {
Добавил функцию func (base *DB) Start(ctx context.Context) error и проверку ошибки при инициализации DB

2023-12-20 15:48 UTC, shulganew commented on internal/web/handlers/batch.go
> +}
Везде исправил

2023-12-20 15:49 UTC, shulganew commented on internal/web/handlers/batch.go
> +func NewHandlerBatch(configApp *config.App) *HandlerBatch {
Исправил

2023-12-20 15:49 UTC, shulganew commented on internal/web/handlers/ping.go
> +func NewDB(configApp *config.App) *Ping {
Исправил

2023-12-21 14:40 UTC, maxlyaptsev approved these changes

2023-12-22 07:19 UTC, merged