Iter15
shulganew/shear pull request #8
Opened 2023-12-26 17:23 UTC by shulganew

Increment 15

2023-12-27 14:31 UTC, maxlyaptsev requested changes

2023-12-27 14:31 UTC, maxlyaptsev commented on internal/web/router/router.go
> +		r.Use(middlewares.MidlewZip)
это же общие мидлвары для всех - можно на уровень выше их установить

2023-12-27 14:31 UTC, maxlyaptsev commented on internal/web/handlers/auth.go
> +			req.AddCookie(cookie)
а зачем брать из реквеста куки и класть обратно?
кажется весь этот блок выше лишний - для работы с куками и авторизацией есть мидлвара

2023-12-27 14:31 UTC, maxlyaptsev commented on internal/web/handlers/auth.go
> +	}
это условие можно сразу проверить наверху и не заворачивать 99% оставшегося кода в условие

2023-12-27 14:31 UTC, maxlyaptsev commented on internal/web/handlers/auth.go
> +package handlers
название файла не соответствует содержимому, это не ручка авторизации

2023-12-27 14:31 UTC, maxlyaptsev commented on internal/web/handlers/del.go
> +		}
копипаста, видел этот же код в auth - явно можно вынести, желательно в мидлвару
можно положить id в контекст для удобства

2023-12-27 14:31 UTC, maxlyaptsev commented on internal/web/handlers/del.go
> +func DeleteGorutine(req *http.Request, userID string, stor *service.Shortener) {
это не ответственность ручки - приняли запрос, проверили - положили в канал/отдали в воркерпул и вернули 200 статус. Дальше должен отработать процесс который получает задачи на обработку и собственно обрабатывает

2023-12-27 14:31 UTC, maxlyaptsev commented on internal/web/handlers/del.go
> +	}()
развалилось форматирование - нужно линтер настроить. Через строку пустая строка

2023-12-27 14:31 UTC, maxlyaptsev commented on internal/web/handlers/del.go
> +
```suggestion
```

2023-12-27 14:31 UTC, maxlyaptsev commented on internal/web/handlers/del.go
> +
```suggestion
```

2023-12-27 14:31 UTC, maxlyaptsev commented on internal/web/handlers/url.go
> +	}
тоже должно быть в мидлваре

2024-01-03 14:10 UTC, shulganew commented on internal/web/router/router.go
> +		r.Use(middlewares.MidlewZip)
Да, я сначала подумал, что ручка удаления пользователя должна обрабатываться отдельно, без общей мидваре, так как есть проверка нового ползователя. Сейчас передаю параметры в контесте запроса и сделал общую мидлварь для все хендлеров.
`
type CtxConfig struct {
	userID    string
	isNewUser bool
}

func NewCtxConfig(userID string, isNewUser bool) CtxConfig {

	return CtxConfig{userID: userID, isNewUser: isNewUser}
}

func (c CtxConfig) GetUserID() string {
	return c.userID
}

func (c CtxConfig) IsNewUser() bool {
	return c.isNewUser
}
`

2024-01-03 14:10 UTC, shulganew commented on internal/web/handlers/auth.go
> +			req.AddCookie(cookie)
Да, все это ушло в мидлварь.

2024-01-03 14:10 UTC, shulganew commented on internal/web/handlers/auth.go
> +	}
Исправил, теперь стараюсь вообще без else писать код.

2024-01-03 14:11 UTC, shulganew commented on internal/web/handlers/auth.go
> +package handlers
Заменил на usersurls.go

2024-01-03 14:11 UTC, shulganew commented on internal/web/handlers/del.go
> +		}
Все убрал в мидлварь.

2024-01-03 14:17 UTC, shulganew commented on internal/web/handlers/del.go
> +func DeleteGorutine(req *http.Request, userID string, stor *service.Shortener) {
Перенес функции в пакет service, по структуре пакета еще хотел обсудить на 1:1, Сергей Ш рассказывал на вебинаре о гексагональной архитектруе, я пару раз прослушал, логику понимаю, а как в структуре кода отоборазить - не уверен. 
Еще я добавил реализацию fanIn, как я понял, так один в водин как в паттерне через массив нельзя реализовать, создаю канал в хендлере и пишу в общий.

2024-01-03 14:17 UTC, shulganew commented on internal/web/handlers/url.go
> +	}
Убрал

2024-01-03 15:03 UTC, shulganew commented on internal/web/handlers/del.go
> +	}()
Исправил

2024-01-09 19:57 UTC, maxlyaptsev commented on internal/web/handlers/del.go
> +func DeleteGorutine(req *http.Request, userID string, stor *service.Shortener) {
Суть в том чтобы в ручке использовать сервис который умеет удалять асинхронно, но больше ничего в ней не писать:

asyncDeleter.DeleteURL(url)

А вся реализация удаления происходит где-то в недрах этого сервиса

2024-01-11 10:14 UTC, shulganew commented on internal/web/handlers/del.go
> +func DeleteGorutine(req *http.Request, userID string, stor *service.Shortener) {
Перенес в одтельный сервис. Еще добавил два теста с мокированием и добавил миграции.
```
	//async delete Shorts from body
	d.serviceDel.AsyncDelete(userID, dec)
```

2024-02-01 14:03 UTC, merged