Iter18
shulganew/shear pull request #9
Opened 2024-02-26 16:17 UTC by shulganew

Sprint 7 Igor's pull request.

2024-02-29 14:43 UTC, maxlyaptsev commented
<img width="1780" alt="image" src="https://github.com/shulganew/shear/assets/10906726/ec665455-e730-47b5-9873-44feada18e0a">

вот я собрал профиль

2024-02-29 14:46 UTC, maxlyaptsev requested changes

2024-02-29 14:46 UTC, maxlyaptsev commented on internal/service/shortener_test.go
> +func BenchmarkShortener(b *testing.B) {
тут можно поработать над алокациями - 13 и 21 довольно много для такого функционала. Не критично, но если получится тут что-то оптимизировать будет хорошо

<img width="1016" alt="image" src="https://github.com/shulganew/shear/assets/10906726/feeb6e7d-f6ae-43b3-9afa-eddb40d1cf86">

2024-03-04 16:42 UTC, shulganew commented on internal/service/shortener_test.go
> +func BenchmarkShortener(b *testing.B) {
Сделал еще один метод GetAnsURLFast, 4 аллокации, только он без URL join, просто конкатинация. С методом кодирования и декодирования идей нет, там стандартные библиоткеки вроде, ничего не придумал.
```
BenchmarkShortener/get_URL-8              681421              1777 ns/op             640 B/op         13 allocs/op
BenchmarkShortener/get_URL_Fast-8        1401660               787.2 ns/op           248 B/op          4 allocs/op
```

2024-03-04 16:54 UTC, shulganew commented
Я добавил нагрузочное тестирование vegeta (/shear/cmd/vegeta/main.go),  написал нагрузочные тесты для каждой ручки. Как я понял, без нагрузки нормальный профиль не собрать. Вот, что получилось:

[https://github.com/shulganew/shear/blob/iter18/profiles/result.png](url)

2024-03-04 18:18 UTC, maxlyaptsev approved these changes

2024-03-05 10:27 UTC, merged